name: Deploy expense-tracker-app

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Installing Nodejs
        uses: actions/setup-node@v2-beta
        with:
          node-version: 12

      - name: Installing Yarn
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: install

      - name: expense-tacker-app
        run: |
          cd expense-tacker-app
          npm run build
      # Runs a set of commands using the runners shell
      - name: Installing Surge To Deploy
        run: npm install -g surge

      - name: Deploy To Surge
        run: surge ./build shehzad-expense-tracker-app-bootcamp.surge.sh --token ${{secrets.SURGE_TOKEN}}
